### ISSUE TITLE
Delete Card confirmation

### ISSUE THREAD

**Issue by Sh4dowsand** [GVigne/TheSleepingLion#4]
**Is your feature request related to a problem? Please describe.**
While I've never actually done it, the fact that the 'Delete Card' button immediately deletes the entire card with no way to undo it concerns me.

**Describe the solution you'd like**
A simple 'Are you sure?' dialog would make me feel a lot safer.

**Describe alternatives you've considered**
Alternatively, having an 'Undo Delete Card' button would also work.

**Comment by GVigne** [comment]
I think having an *Undo Delete Card* button would be a bit redundant with a generic *Undo* function. For most softwares, Ctrl+Z can revert any change, so it would be nice to mimic that. It would require quite some changes as I might need to implement a better structure (a state machine maybe?) to keep everything in order.

Adding a simple “Confirm delete card” popup is reasonable and easy to implement – and it’s always a good feature to have, so I’m going to add this.
