### ISSUE TITLE
File -> New

### ISSUE THREAD

**Issue by Sh4dowsand** [GVigne/TheSleepingLion#5]
**Is your feature request related to a problem? Please describe.**
There seems to be no in-app method of starting a new file. You have to close the app, then open it again. Not a big problem, but slightly irritating.

**Describe the solution you'd like**
Having a 'New' option under the 'File' menu would be the ideal solution. Clicking it would have the same effects as closing/reopening the app (including the 'Discard unsaved changes?' dialogue, when there are any).

**Comment by GVigne** [comment]
I guess this shows that I’m too focused on the code and don’t do enough testing :) It’s such a basic feature I should’ve implemented that before. Thanks for the input!

**Comment by GVigne** [comment]
This was fixed in 7b4745537cc9014ff6ba5bbd91d5940274fab419.
Thank you again for raising this issue!
